player = {
    "name": "gamer",
    "gold": 0,
    "weapon": "fists",
    "armor": "clothes",
    "health": 100,
    "stamina": 50,
    "mana": 10,
    "strength": 0,
    "intellect": 0,
    "agility": 0,
    "constitution": 0,
    "physical": 0,
    "magicka": 0,
    "ranged": 0,
    "dodge": 0,
    "stealth": 0,
    "phys_miti": 0,
    "magi_miti": 0,
    "rang_miti": 0,
    "phys_mult": 0,
    "magi_mult": 0,
    "rang_mult": 0,
    "phys_resi": 0,
    "magi_resi": 0,
    "rang_resi": 0,
    "health_mult": 0,
}